#SPDX-License-Identifier: MIT-0
---
# tasks file for docker

- name: Remove unofficial packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
      - docker-compose2
      - docker-doc
      - podman-docker
    state: absent


